language: cpp

before_install:
  - sudo apt-get install g++-4.9
  - sudo apt-get install gcc-4.9
  - export CC=gcc-4.9
  - export CXX=g++-4.9
  - sudo pip install cpp-coveralls
  - sudo apt-get install lcov
  - sudo unlink /usr/bin/gcov && sudo ln -s /usr/bin/gcov-4.9 /usr/bin/gcov

script:
  - make coveralls

after_success:
  - make send-coveralls
