language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

install:
  - git clone https://github.com/linux-test-project/lcov.git
  - cd lcov && make install PREFIX=. && cd ..
  - export PATH=$PWD/lcov/usr/bin:$PATH
  - export CXX=g++-5 && export CXX=gcc
  - chmod 777 -R lcov && cp $(which gcov-5) lcov/usr/bin/
  - gem install coveralls-lcov

# script: make coverage
script:
  - gcov --version
  - lcov --version

# after_success: coveralls-lcov build/coverage/coverage.info.cleaned
