language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - debootstrap
      - fakechroot
      - fakeroot
      - g++-5
      - gcc-5

install:
  - fakechroot fakeroot debootstrap precise installed
  - fakechroot fakeroot chroot installed ci/install_gcc5.sh
  - fakechroot fakeroot chroot installed ci/install_lcov111.sh
  - export PATH=installed/usr/bin:$PATH
  - gem install coveralls-lcov

# script: make coverage
script:
  - which g++
  - which gcc
  - which gcov
  - which lcov

# after_success: coveralls-lcov build/coverage/coverage.info.cleaned
