language: cpp

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-5
  - sudo apt-get install gcc-5
  - export CC=gcc-5
  - export CXX=g++-5
  - wget http://launchpadlibrarian.net/178468692/lcov_1.11-2_all.deb
  - sudo dpkg -i lcov_1.11-2_all.deb
  - sudo unlink /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov
  - sudo pip install cpp-coveralls

script:
  - make coveralls

after_success:
  - coveralls --exclude test --exclude googletest
