language: cpp

addons:
  apt:
    packages:
      - debootstrap

install:
  - debootstrap precise installed
  - chroot installed
  - ci/install_gcc5.sh
  - ci/install_lcov111.sh
  - exit # from chroot
  - gem install coveralls-lcov

# script: make coverage
script:
  - which g++
  - which gcc
  - which gcov
  - which lcov

# after_success: coveralls-lcov build/coverage/coverage.info.cleaned
