language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

install:
  - git clone git clone https://github.com/linux-test-project/lcov.git
  - cd lcov && make install PREFIX=../lcov-installed
  - export PATH=lcov-installed/usr/bin:$PATH
  - export CXX=g++-5 && export CXX=gcc
  - gem install coveralls-lcov

# script: make coverage
script:
  - which g++
  - which gcc
  - which gcov
  - which lcov

# after_success: coveralls-lcov build/coverage/coverage.info.cleaned
