language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

install:
  - git clone https://github.com/linux-test-project/lcov.git
  - mkdir -p installed && cd lcov && make install PREFIX=../installed && cd ..
  - export PATH=$PWD/installed/usr/bin:$PATH
  - export CXX=g++-5 && export CC=gcc
  - ln -s $(which gcov-5) installed/usr/bin/gcov
  - gem install coveralls-lcov

script: make coverage

after_success: coveralls-lcov build/coverage/coverage.info.cleaned
