language: cpp

before_install:
  - export CXX=g++-5 && CC=gcc-5
  - sudo ci/install_lcov111.sh
  - gem install coveralls-lcov

script:
  - make coveralls

after_success:
  - coveralls-lcov build/coverage/coverage.info.cleaned
