language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

install:
  - ci/install_lcov.sh
  - ci/fix_symlinks.sh
  - export PATH=$PWD/usr/bin/:$PATH
  - gem install coveralls-lcov

script: make coverage

after_success: ci/upload_coverage.sh
