language: cpp

before_install:
  - sudo ci/fix_gcc_symlinks.sh
  - sudo ci/install_lcov111.sh
  - gem install coveralls-lcov

script:
  - make coveralls

after_success:
  - coveralls-lcov build/coverage/coverage.info.cleaned
