language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

install:
  - PREFIX=installed ci/install_to_custom_path.sh
  - export PATH=$PWD/installed/usr/bin:$PATH
  - gem install coveralls-lcov

script: make coverage

after_success: coveralls-lcov build/coverage/coverage.info.cleaned
