language: cpp

before_install:
  - sudo ci/install_gcc5.sh
  - sudo ci/install_lcov111.sh
  - gem install coveralls-lcov

script:
  - make coverage

after_success:
  - coveralls-lcov build/coverage/coverage.info.cleaned
