language: cpp

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-5
  - sudo apt-get install gcc-5
  - export CC=gcc-5
  - export CXX=g++-5
  - sudo pip install cpp-coveralls
  - wget http://downloads.sourceforge.net/ltp/lcov-1.11.tar.gz
  - tar -xzf lcov-1.11.tar.gz && cd lcov-1.11 && make && sudo make install $$ cd ..
  - sudo unlink /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov

script:
  - make coveralls

after_success:
  - make send-coveralls
