language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - ninja-build

env:
  - BUILD_SYSTEM=make
  - BUILD_SYSTEM=ninja

install:
  - ci/install_lcov.sh
  - gem install coveralls-lcov
  - ci/fix_symlinks.sh
  - export PATH=$PWD/usr/bin/:$PATH

script: $BUILD_SYSTEM coverage

after_success: ci/upload_coverage.sh